spring.application.name=Tour
spring.datasource.url=jdbc:postgresql://localhost:5432/Tour_Application
spring.datasource.username=furkan
spring.datasource.password=Developer2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect