package com.project.btoproject.enums;

public enum Status{
    NEW_TOUR_APPLICATION,
    BTO_ACCEPTED,
    BTO_REJECTED,
    UPCOMING_TOUR,
    TOUR_IN_PROGRESS,
    COMPLETED_TOUR,
    CANCELED_TOUR,
    NEW_FAIR_APPLICATION,
    UPCOMING_FAIR,
    REJECTED_FAIR,
    CANCELED_FAIR,
    COMPLETED_FAIR,
    NEW_INDIVIDUAL_TOUR_APPLICATION,
    REJECTED_INDIVIDUAL_TOUR_APPLICATION,
    UPCOMING_INDIVIDUAL_TOUR,
    COMPLETED_INDIVIDUAL_TOUR,
    CANCELED_INDIVIDUAL_TOUR
}